[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "3dvton-bat"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "numpy==1.26.1",
    "Pillow",
    "huggingface_hub",
    "einops",
    "safetensors",
    "jupyter",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["3dvton"]
